### ISSUE TITLE
Unable to down load file from CSSEGISandData

### ISSUE THREAD

**Issue by andrewyimingchen** [liuyanguu/Blogdown#1]
Hi, I recently came upon your blog and find your GitHub page, I was able to replicate what you did on your recent heatmap post on covid19 yesterday. For some reason, using the exact same code from your page gives an error message today. 

dt_JUH_US <- get.JHU.us.state()

Error in curl::curl_download(input, tmpFile, mode = "wb", quiet = !showProgress) : 
  HTTP error 404.

**Comment by liuyanguu** [comment]
I guess it is because we are on different time-zones. 
`get.JHU.us.state()` is just: 
```
get.JHU.us.state <- function(){
  date0 <- format(Sys.Date()-1, format = "%m-%d-%Y")
  url_us_daily_report <- paste0("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/", as.character(date0) ,".csv")
  dt_JUH_US <- fread(url_us_daily_report)
  dt_JUH_US
}
```
Maybe try
```
 date0 <- format(Sys.Date()-2, format = "%m-%d-%Y") 
```
All the available datasets are :
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us

**Comment by andrewyimingchen** [comment]
It works, thanks! 
One more question, I know Sys.Date() function is for getting current time, but why would this matter if you were directly trying to get the CSV file from Github? 
Apology, if I ask rudimentary questions.

**Comment by liuyanguu** [comment]
No problem. Thanks for the question. It's just there is a dataset uploaded every day (in the [link ](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us)I wrote above), and I used ` Sys.Date()` to (try to) get the latest one. It is used to create the web link of the file that I wish to download.

**Comment by andrewyimingchen** [comment]
ahhh, got it. Thanks for the explanation! 

Cheers mate!
